# Generated by Django 4.1.5 on 2024-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='heading',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(),
        ),
    ]
