# Generated by Django 4.1.5 on 2024-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_project_category_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('AI', 'AI'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development'), ('Finance', 'Finance'), ('IoT', 'IoT'), ('App Development', 'App Development'), ('Health', 'Health'), ('Productivity', 'Productivity'), ('Entertainment', 'Entertainment'), ('E-commerce', 'E-commerce'), ('Education', 'Education'), ('Cloud', 'Cloud'), ('Sports', 'Sports'), ('Robotics', 'Robotics'), ('Drones', 'Drones'), ('Mechanical', 'Mechanical'), ('Cybersecurity', 'Cybersecurity'), ('Ar/Vr', 'Ar/Vr'), ('Blockchain', 'Blockchain'), ('Environmental Sustainability', 'Environmental Sustainability')], max_length=100),
        ),
    ]
