# Generated by Django 4.1.5 on 2024-03-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('AI', 'AI'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development')], max_length=100),
        ),
    ]
