# Generated by Django 4.1.5 on 2024-03-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.CharField(choices=[('AI', 'AI'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development'), ('Finance', 'Finance'), ('Iot', 'Iot'), ('App Development', 'App Development'), ('Health', 'Health'), ('Productivity', 'Productivity'), ('Entertainment', 'Entertainment'), ('E-commerce', 'E-commerce'), ('Education', 'Education'), ('Cloud', 'Cloud'), ('Sports', 'Sports'), ('Robotics', 'Robotics'), ('Drones', 'Drones'), ('Mechanical', 'Mechanical'), ('Cybersecurity', 'Cybersecurity'), ('Ar/Vr', 'Ar/Vr'), ('Blockchain', 'Blockchain'), ('Environmental Sustainability', 'Environmental Sustainability')], default='default_value', max_length=100),  # Change 'default_value' to your desired default value
        ),
    ]
