# Generated by Django 4.1.5 on 2024-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_project_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='AI', max_length=100),
            preserve_default=False,
        ),
    ]
