# Generated by Django 4.1.5 on 2024-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_project_category_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='AI', max_length=100),
            preserve_default=False,
        ),
    ]
