# Generated by Django 4.1.5 on 2024-04-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_project_tags_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected_tags',
            field=models.CharField(default='AI', max_length=255),
            preserve_default=False,
        ),
    ]
