# Generated by Django 4.1.5 on 2024-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_project_selected_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected_tags_text',
            field=models.TextField(default='AI'),
            preserve_default=False,
        ),
    ]
