# Generated by Django 4.1.5 on 2024-04-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_project_selected_tags_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='selected_tags_text',
        ),
    ]
