# Generated by Django 5.0.4 on 2024-04-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_chatmessage'),
        ('myapp', '0030_remove_project_selected_tags_text'),
    ]

    operations = [
    ]
