# Generated by Django 5.0.4 on 2024-04-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_merge_20240420_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='Noida', max_length=100),
            preserve_default=False,
        ),
    ]
